#!/usr/bin/env python
"""
Download a compound from PubChem (3D) to an SDF file.

Note: For structures that do not contain a 3D structure,
in pubchem, we will attempt to resolve them by getting
the structure of the parent compound.

"""
from __future__ import print_function, absolute_import
import pubchem_utils
import traceback
import argparse
from six.moves.urllib.error import HTTPError


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('cid')
    parser.add_argument('outfile')
    args = parser.parse_args()

    download_cid(args.cid, args.outfile)


def download_cid(cid, filename):
    pc = pubchem_utils.PubChem()

    try:
        print('Downloading CID %s...' % cid)
        pc.get_record(cid, filename=filename, use_3d=True)
    except HTTPError as e:
        traceback.print_exc(limit=1)
        if e.code == 404:
            print('Resolving parent CID...')
            pcid = next(iter(pc.get_parent_cids([cid])))
            return download_cid(pcid, filename)
    print('Output (SDF) saved to %s' % filename)


if __name__ == '__main__':
    main()
